[package]
name = "kerosene-membership"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []
production = ["kerosene-contracts/production"]

[dependencies]
ed25519-dalek.workspace = true
hex.workspace = true
kerosene-contracts.workspace = true
thiserror.workspace = true
url.workspace = true

[dev-dependencies]
kerosene-identity-core = { path = "../kerosene-identity-core" }
