name: Release kerosene-rsctl

on:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    uses: Daniel-Astrofer/.github/.github/workflows/rust-release.yml@22187a79ff528ae7c31b9b13ec6903c11807f9a9
    with:
      package: kerosene-rsctl
      features: production
      forbidden-features: dealer_lab
