name: Repository Security

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  security:
    uses: Daniel-Astrofer/.github/.github/workflows/security-scan.yml@3cfcdc140bb715528505383a6987ab2200556d37
